### ISSUE TITLE
uniform the parameters for the CLIs

### ISSUE THREAD

**Issue by albarron** [cristinae/WikiTailor#10]
We should come out with a list of all the flags in the different CLIs and get sure they are consisted (e.g., x means the same everywhere)

**Comment by cristinae** [comment]
This is checked for the main WT/IR classes. Experiments and utilities have to be homogenised with the main classes (nomenclature, external CLIs, patterns, etc) if they are to be included in the main distribution.

**Comment by albarron** [comment]
What about adding this to the Wiki? That would allow for a quick look/update when designing new CLIs

**Comment by cristinae** [comment]
Do we have a Wiki?!

**Comment by albarron** [comment]
oh yeah!

https://github.com/cristinae/WikiTailor/wiki

**Comment by cristinae** [comment]
Ok for me then. But we have to mantain:
1) The manual
2) The web page
3) The wiki

**Comment by cristinae** [comment]
Please, check if you meant something like this in order to continue with more classes:
https://github.com/cristinae/WikiTailor/wiki/Parameters-for-the-CLIs

**Comment by albarron** [comment]
Exactly!
