### ISSUE TITLE
The thirdparty dependencies should not be included

### ISSUE THREAD

**Issue by albarron** [cristinae/WikiTailor#2]
Libraries coming from third parties should not be part of the project. We could create some script, probably ant itself, to download the necessary dependencies independently of the project git repository.

I can do that task

**Comment by cristinae** [comment]
In this case we should deliver a WTwithdependencies jar. We use old versions of the libraries in some cases and even for recent libraries, links change with time. Getting the libraries shouldn't be a problem for a user.

There is a script that downloads the libraries in the web page. You can "antize" it if you want.

**Comment by albarron** [comment]
As part of the migration to maven, now no dependencies are included
