### ISSUE TITLE
7 projects within one repository

### ISSUE THREAD

**Issue by albarron** [cristinae/WikiTailor#3]
IMHO, here we have one single repository for seven projects. Each project should lice in its own repository. Obviously, dependencies can exist across projects.

**Comment by cristinae** [comment]
In fact, there shouldn't be 7 projects. My proposal is to do a version 2 of the software with only one, or at most two projects: 
The WT-related stuff:
   lump-aq-textextraction
   lump-aq-wikilink
   lump-ie-textprocessing
   lump-ir-lucene,
and the generic stuff:
   lump-aq-basics
   lump-ir-retrievalmodels
   lump-ir-sim.

I'd like to do only one clone to download WT, if we move now to 7 repositories it will be a mess. Am I wrong?

**Comment by albarron** [comment]
Maybe this is the right time to both switch to one (or two) projects  and switch to maven at the same time?

**Comment by albarron** [comment]
The projects were merged into one
